import type { SimpleIcon } from "simple-icons";
import {
  siAirtable,
  siAsana,
  siCalendly,
  siCloudflare,
  siDiscord,
  siDropbox,
  siFacebook,
  siFigma,
  siGithub,
  siGitlab,
  siGmail,
  siGoogle,
  siGoogleads,
  siGoogleanalytics,
  siGooglecalendar,
  siGoogledrive,
  siHubspot,
  siInstagram,
  siIntercom,
  siJira,
  siLinear,
  siMailchimp,
  siMercadopago,
  siMeta,
  siN8n,
  siNetlify,
  siNotion,
  siPaypal,
  siPinterest,
  siShopify,
  siStripe,
  siSupabase,
  siTelegram,
  siTiktok,
  siTrello,
  siTypeform,
  siVercel,
  siWhatsapp,
  siWoocommerce,
  siWordpress,
  siX,
  siYoutube,
  siZapier,
  siZendesk,
  siZoom,
} from "simple-icons";

// Brand marks from simple-icons (CC0). Brands whose owners asked simple-icons
// to remove their logo (Slack, LinkedIn, Amazon, Salesforce, Canva, Twilio,
// Microsoft) fall back to initials.
const ICONS: Record<string, SimpleIcon> = {
  airtable: siAirtable,
  asana: siAsana,
  calendly: siCalendly,
  cloudflare: siCloudflare,
  discord: siDiscord,
  dropbox: siDropbox,
  "facebook-pages": siFacebook,
  figma: siFigma,
  github: siGithub,
  gitlab: siGitlab,
  gmail: siGmail,
  "google-workspace": siGoogle,
  "google-ads": siGoogleads,
  "google-analytics": siGoogleanalytics,
  "google-calendar": siGooglecalendar,
  "google-drive": siGoogledrive,
  hubspot: siHubspot,
  instagram: siInstagram,
  intercom: siIntercom,
  jira: siJira,
  linear: siLinear,
  mailchimp: siMailchimp,
  "mercado-livre": siMercadopago,
  "mercado-pago": siMercadopago,
  "meta-ads": siMeta,
  n8n: siN8n,
  netlify: siNetlify,
  notion: siNotion,
  paypal: siPaypal,
  pinterest: siPinterest,
  shopify: siShopify,
  stripe: siStripe,
  supabase: siSupabase,
  telegram: siTelegram,
  "tiktok-business": siTiktok,
  trello: siTrello,
  typeform: siTypeform,
  vercel: siVercel,
  whatsapp: siWhatsapp,
  woocommerce: siWoocommerce,
  wordpress: siWordpress,
  "x-twitter": siX,
  youtube: siYoutube,
  zapier: siZapier,
  zendesk: siZendesk,
  zoom: siZoom,
};

export type ConnectorIcon = { path: string; color: string; title: string };

// connectorIcon returns the brand mark for a catalog id. Near-black brand
// colors return "currentColor" so the mark stays visible in dark mode.
export function connectorIcon(id: string): ConnectorIcon | null {
  const icon = ICONS[id];
  if (!icon) return null;
  const hex = icon.hex.toLowerCase();
  const dark = hex === "000000" || hex === "181717" || hex === "010101";
  return {
    path: icon.path,
    color: dark ? "currentColor" : `#${icon.hex}`,
    title: icon.title,
  };
}
