import type { SimpleIcon } from "simple-icons";
import {
  siAlgolia,
  siAppwrite,
  siAuth0,
  siBetterstack,
  siBitbucket,
  siBrevo,
  siCircleci,
  siClerk,
  siCloudinary,
  siContentful,
  siCoolify,
  siDatadog,
  siDeepgram,
  siDigitalocean,
  siDocker,
  siElevenlabs,
  siExpo,
  siFirebase,
  siFlydotio,
  siGooglecloud,
  siGrafana,
  siHetzner,
  siHostinger,
  siHuggingface,
  siLemonsqueezy,
  siLivekit,
  siMeilisearch,
  siMixpanel,
  siMongodb,
  siNeon,
  siNovu,
  siPaddle,
  siPagseguro,
  siPlanetscale,
  siPocketbase,
  siPostgresql,
  siPosthog,
  siPrisma,
  siPusher,
  siQdrant,
  siRailway,
  siRedis,
  siRender,
  siReplicate,
  siResend,
  siSanity,
  siSentry,
  siStrapi,
  siUpstash,
} from "simple-icons";
import {
  siAirtable,
  siAsana,
  siCalendly,
  siCloudflare,
  siDiscord,
  siDropbox,
  siFacebook,
  siFigma,
  siGithub,
  siGitlab,
  siGmail,
  siGoogle,
  siGoogleads,
  siGoogleanalytics,
  siGooglecalendar,
  siGoogledrive,
  siHubspot,
  siInstagram,
  siIntercom,
  siJira,
  siLinear,
  siMailchimp,
  siMercadopago,
  siMeta,
  siN8n,
  siNetlify,
  siNotion,
  siPaypal,
  siPinterest,
  siShopify,
  siStripe,
  siSupabase,
  siTelegram,
  siTiktok,
  siTrello,
  siTypeform,
  siVercel,
  siWhatsapp,
  siWoocommerce,
  siWordpress,
  siX,
  siYoutube,
  siZapier,
  siZendesk,
  siZoom,
} from "simple-icons";

// Brand marks from simple-icons (CC0). Brands it does not distribute use the
// bundled images in IMAGE_ICONS below.
const ICONS: Record<string, SimpleIcon> = {
  resend: siResend,
  brevo: siBrevo,
  firebase: siFirebase,
  appwrite: siAppwrite,
  pocketbase: siPocketbase,
  postgresql: siPostgresql,
  mongodb: siMongodb,
  neon: siNeon,
  planetscale: siPlanetscale,
  redis: siRedis,
  upstash: siUpstash,
  prisma: siPrisma,
  qdrant: siQdrant,
  "huggingface-hub": siHuggingface,
  replicate: siReplicate,
  elevenlabs: siElevenlabs,
  deepgram: siDeepgram,
  "google-cloud": siGooglecloud,
  digitalocean: siDigitalocean,
  railway: siRailway,
  render: siRender,
  flyio: siFlydotio,
  hetzner: siHetzner,
  hostinger: siHostinger,
  coolify: siCoolify,
  "docker-hub": siDocker,
  bitbucket: siBitbucket,
  circleci: siCircleci,
  sentry: siSentry,
  datadog: siDatadog,
  grafana: siGrafana,
  betterstack: siBetterstack,
  posthog: siPosthog,
  mixpanel: siMixpanel,
  auth0: siAuth0,
  clerk: siClerk,
  algolia: siAlgolia,
  meilisearch: siMeilisearch,
  cloudinary: siCloudinary,
  contentful: siContentful,
  sanity: siSanity,
  strapi: siStrapi,
  pusher: siPusher,
  livekit: siLivekit,
  novu: siNovu,
  expo: siExpo,
  "lemon-squeezy": siLemonsqueezy,
  paddle: siPaddle,
  pagseguro: siPagseguro,
  airtable: siAirtable,
  asana: siAsana,
  calendly: siCalendly,
  cloudflare: siCloudflare,
  discord: siDiscord,
  dropbox: siDropbox,
  "facebook-pages": siFacebook,
  figma: siFigma,
  github: siGithub,
  gitlab: siGitlab,
  gmail: siGmail,
  "google-workspace": siGoogle,
  "google-ads": siGoogleads,
  "google-analytics": siGoogleanalytics,
  "google-calendar": siGooglecalendar,
  "google-drive": siGoogledrive,
  hubspot: siHubspot,
  instagram: siInstagram,
  intercom: siIntercom,
  jira: siJira,
  linear: siLinear,
  mailchimp: siMailchimp,
  "mercado-livre": siMercadopago,
  "mercado-pago": siMercadopago,
  "meta-ads": siMeta,
  n8n: siN8n,
  netlify: siNetlify,
  notion: siNotion,
  paypal: siPaypal,
  pinterest: siPinterest,
  shopify: siShopify,
  stripe: siStripe,
  supabase: siSupabase,
  telegram: siTelegram,
  "tiktok-business": siTiktok,
  trello: siTrello,
  typeform: siTypeform,
  vercel: siVercel,
  whatsapp: siWhatsapp,
  woocommerce: siWoocommerce,
  wordpress: siWordpress,
  "x-twitter": siX,
  youtube: siYoutube,
  zapier: siZapier,
  zendesk: siZendesk,
  zoom: siZoom,
};

// Official favicons, fetched once from each brand's own site and shipped in
// public/connector-icons, for brands that simple-icons does not distribute.
const IMAGE_ICONS: Record<string, string> = {
  "amazon-seller": "amazon-seller.png",
  asaas: "asaas.png",
  aws: "aws.png",
  azure: "azure.png",
  canva: "canva.jpg",
  composio: "composio.png",
  "fiscal-ai": "fiscal-ai.png",
  linkedin: "linkedin.png",
  outlook: "outlook.jpg",
  pagarme: "pagarme.png",
  pinecone: "pinecone.png",
  postmark: "postmark.png",
  salesforce: "salesforce.png",
  sendgrid: "sendgrid.png",
  slack: "slack.png",
  twilio: "twilio.png",
  "woovi-openpix": "woovi-openpix.png",
};

export type ConnectorIcon =
  | { kind: "svg"; path: string; color: string; title: string }
  | { kind: "image"; src: string }
  | { kind: "generic" };

// connectorIcon returns the mark for a catalog id: a simple-icons SVG, a
// bundled brand image, or a generic document icon for non-brand entries.
// Near-black SVG colors return "currentColor" to stay visible in dark mode.
export function connectorIcon(id: string): ConnectorIcon {
  const icon = ICONS[id];
  if (icon) {
    const hex = icon.hex.toLowerCase();
    const dark = hex === "000000" || hex === "181717" || hex === "010101";
    return {
      kind: "svg",
      path: icon.path,
      color: dark ? "currentColor" : `#${icon.hex}`,
      title: icon.title,
    };
  }
  const image = IMAGE_ICONS[id];
  if (image) return { kind: "image", src: `/connector-icons/${image}` };
  return { kind: "generic" };
}
