package agent

import "sort"

type ConnectorCatalogEntry struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Category    string   `json:"category"`
	Kind        string   `json:"kind"`
	Description string   `json:"description"`
	Auth        string   `json:"auth"`
	Source      string   `json:"source"`
	Status      string   `json:"status"`
	Scopes      []string `json:"scopes,omitempty"`
}

// ConnectorCatalog is intentionally a capability catalog, not a claim that every
// provider is connected. Entries requiring an operator credential remain explicit.
func ConnectorCatalog() []ConnectorCatalogEntry {
	entries := []ConnectorCatalogEntry{
		{ID: "github", Name: "GitHub", Category: "Desenvolvimento", Kind: "app", Description: "Repositórios, branches, issues, pull requests, Actions e releases.", Auth: "oauth", Source: "built-in/example", Status: "available", Scopes: []string{"repositories", "issues", "pull_requests", "actions"}},
		{ID: "google-workspace", Name: "Google Workspace", Category: "Produtividade", Kind: "app", Description: "Gmail, Drive, Docs, Sheets, Calendar e contatos.", Auth: "oauth", Source: "built-in", Status: "available", Scopes: []string{"gmail", "drive", "docs", "sheets", "calendar"}},
		{ID: "composio", Name: "Composio", Category: "Automação", Kind: "mcp", Description: "Gateway MCP para aplicativos autorizados pelo operador, com descoberta de ferramentas.", Auth: "oauth_or_api_key", Source: "mcp", Status: "available", Scopes: []string{"tool_discovery", "oauth", "external_actions"}},
		{ID: "slack", Name: "Slack", Category: "Comunicação", Kind: "app", Description: "Mensagens, canais, threads e notificações com aprovação para efeitos externos.", Auth: "oauth", Source: "built-in/example", Status: "available", Scopes: []string{"messages", "channels"}},
		{ID: "discord", Name: "Discord", Category: "Comunicação", Kind: "custom_api", Description: "Bots, canais e mensagens via aplicação Discord ou Composio.", Auth: "bot_or_oauth", Source: "custom_api/mcp", Status: "operator_setup_required", Scopes: []string{"messages", "channels"}},
		{ID: "whatsapp", Name: "WhatsApp Business", Category: "Comunicação", Kind: "custom_api", Description: "Mensagens transacionais pela WhatsApp Cloud API/Meta Business.", Auth: "api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"messages", "templates"}},
		{ID: "notion", Name: "Notion", Category: "Produtividade", Kind: "app", Description: "Páginas, databases, blocos e conhecimento operacional.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"pages", "databases"}}, //nolint:misspell // Portuguese catalog copy.
		{ID: "jira", Name: "Jira", Category: "Desenvolvimento", Kind: "custom_api", Description: "Projetos, issues, sprints e workflow de engenharia.", Auth: "oauth_or_api_key", Source: "custom_api/mcp", Status: "operator_setup_required", Scopes: []string{"issues", "projects"}},
		{ID: "hubspot", Name: "HubSpot", Category: "CRM e Vendas", Kind: "app", Description: "CRM, contatos, empresas, negócios e automações comerciais.", Auth: "oauth", Source: "built-in", Status: "available", Scopes: []string{"crm", "contacts"}},
		{ID: "stripe", Name: "Stripe", Category: "Pagamentos", Kind: "app", Description: "Clientes, produtos, invoices e webhooks; movimentações sensíveis permanecem approval-gated.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"customers", "products", "invoices", "webhooks"}}, //nolint:misspell // Portuguese catalog copy.
		{ID: "woovi-openpix", Name: "Woovi / OpenPix", Category: "Pagamentos", Kind: "custom_api", Description: "Cobranças Pix, QR Code, conciliação e webhooks de pagamento em tempo real.", Auth: "api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"charges", "webhooks", "transactions"}},
		{ID: "fiscal-invoicing", Name: "Emissão fiscal NF-e/NFS-e", Category: "Fiscal", Kind: "custom_api", Description: "Contrato para emissão, consulta, cancelamento e armazenamento de XML/DANFE por provedor fiscal homologado.", Auth: "api_key_or_certificate", Source: "custom_api", Status: "provider_selection_required", Scopes: []string{"nfe", "nfse", "xml", "danfe", "webhooks"}},
		{ID: "fiscal-ai", Name: "Fiscal AI", Category: "Dados financeiros", Kind: "mcp", Description: "Dados financeiros e análises de empresas; não é emissor de NF-e/NFS-e.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"financial_data", "filings"}},
		{ID: "instagram", Name: "Instagram", Category: "Marketing", Kind: "app", Description: "Contas profissionais, conteúdo e métricas via permissões da Meta.", Auth: "oauth", Source: "built-in", Status: "available", Scopes: []string{"content", "insights"}},
		{ID: "meta-ads", Name: "Meta Ads Manager", Category: "Marketing", Kind: "app", Description: "Campanhas, anúncios, orçamento e métricas com approval para publicação e gasto.", Auth: "oauth", Source: "built-in", Status: "available", Scopes: []string{"campaigns", "insights", "ads"}},
		{ID: "tiktok-business", Name: "TikTok for Business", Category: "Marketing", Kind: "app", Description: "Campanhas e métricas TikTok; TikTok Shop depende de elegibilidade e APIs da conta.", Auth: "oauth", Source: "built-in", Status: "available", Scopes: []string{"campaigns", "insights"}},
		{ID: "shopify", Name: "Shopify", Category: "Comércio", Kind: "app", Description: "Produtos, inventário, pedidos e fulfillment com aprovação antes de efeitos comerciais.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"products", "inventory", "orders"}},
		{ID: "woocommerce", Name: "WooCommerce", Category: "Comércio", Kind: "custom_api", Description: "Catálogo, pedidos e estoque via REST API do operador.", Auth: "api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"products", "orders", "inventory"}},
		{ID: "mercado-livre", Name: "Mercado Livre", Category: "Comércio", Kind: "custom_api", Description: "Catálogo, pedidos, anúncios e logística conforme permissões da conta.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"catalog", "orders", "shipping"}},
		{ID: "amazon-seller", Name: "Amazon Seller", Category: "Comércio", Kind: "custom_api", Description: "Produtos, pedidos e fulfillment pela Selling Partner API.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"catalog", "orders", "inventory"}},
		{ID: "vercel", Name: "Vercel", Category: "Deploy", Kind: "app", Description: "Projetos, deployments, domínios e logs de publicação.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"projects", "deployments", "domains"}},
		{ID: "netlify", Name: "Netlify", Category: "Deploy", Kind: "app", Description: "Sites, deploys, domains e logs de publicação.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"sites", "deploys", "domains"}},
		{ID: "cloudflare", Name: "Cloudflare", Category: "Deploy", Kind: "app", Description: "Workers, Pages, DNS e configurações de edge com escopo explícito.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"pages", "workers", "dns"}},
		{ID: "zapier", Name: "Zapier", Category: "Automação", Kind: "mcp", Description: "Ações e workflows externos através de conexão autorizada.", Auth: "oauth_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"actions", "triggers"}},
		{ID: "n8n", Name: "n8n", Category: "Automação", Kind: "mcp", Description: "Workflows self-hosted ou cloud para integrações operacionais.", Auth: "url_or_api_key", Source: "built-in", Status: "available", Scopes: []string{"workflows", "executions"}},
		{ID: "pinterest", Name: "Pinterest", Category: "Marketing", Kind: "custom_api", Description: "Pins, boards, catálogo e métricas de anúncios; publicação exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"pins", "boards", "ads"}},
		{ID: "youtube", Name: "YouTube", Category: "Marketing", Kind: "custom_api", Description: "Canais, vídeos, playlists, comentários e métricas; upload exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"videos", "analytics"}},
		{ID: "linkedin", Name: "LinkedIn", Category: "Marketing", Kind: "custom_api", Description: "Páginas de empresa, posts e métricas; publicação exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"pages", "posts"}},
		{ID: "x-twitter", Name: "X (Twitter)", Category: "Marketing", Kind: "custom_api", Description: "Posts, menções e métricas via API do X; publicação exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"posts", "mentions"}},
		{ID: "facebook-pages", Name: "Facebook Pages", Category: "Marketing", Kind: "custom_api", Description: "Páginas, posts, mensagens e insights via permissões da Meta.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"pages", "posts", "insights"}},
		{ID: "telegram", Name: "Telegram", Category: "Comunicação", Kind: "custom_api", Description: "Bot para receber tarefas e enviar resultados em chats autorizados.", Auth: "bot_token", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"messages"}},
		{ID: "gmail", Name: "Gmail", Category: "Comunicação", Kind: "custom_api", Description: "Ler, buscar e redigir e-mails; envio exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"read", "draft", "send"}},
		{ID: "google-drive", Name: "Google Drive", Category: "Produtividade", Kind: "custom_api", Description: "Arquivos, pastas e compartilhamento com escopo por pasta.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"files"}},
		{ID: "google-calendar", Name: "Google Agenda", Category: "Produtividade", Kind: "custom_api", Description: "Eventos, disponibilidade e convites; criar convite exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"events"}},
		{ID: "google-analytics", Name: "Google Analytics", Category: "Dados e métricas", Kind: "custom_api", Description: "Relatórios GA4 de tráfego, conversão e público.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"reports"}},
		{ID: "google-ads", Name: "Google Ads", Category: "Marketing", Kind: "custom_api", Description: "Campanhas, orçamento e métricas; gasto e publicação exigem approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"campaigns", "reports"}},
		{ID: "outlook", Name: "Outlook / Microsoft 365", Category: "Comunicação", Kind: "custom_api", Description: "E-mail, calendário e contatos via Microsoft Graph; envio exige approval.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"mail", "calendar"}},
		{ID: "trello", Name: "Trello", Category: "Produtividade", Kind: "custom_api", Description: "Quadros, listas e cartões.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"boards", "cards"}},
		{ID: "asana", Name: "Asana", Category: "Produtividade", Kind: "custom_api", Description: "Projetos, tarefas e responsáveis.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"projects", "tasks"}},
		{ID: "linear", Name: "Linear", Category: "Desenvolvimento", Kind: "custom_api", Description: "Issues, ciclos e projetos de engenharia.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"issues", "projects"}},
		{ID: "gitlab", Name: "GitLab", Category: "Desenvolvimento", Kind: "custom_api", Description: "Repositórios, merge requests, issues e pipelines.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"repos", "merge_requests", "pipelines"}},
		{ID: "airtable", Name: "Airtable", Category: "Dados e métricas", Kind: "custom_api", Description: "Bases, tabelas e registros.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"bases", "records"}},
		{ID: "dropbox", Name: "Dropbox", Category: "Produtividade", Kind: "custom_api", Description: "Arquivos e pastas com links de compartilhamento.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"files"}},
		{ID: "figma", Name: "Figma", Category: "Design", Kind: "custom_api", Description: "Arquivos, frames, componentes e comentários de design.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"files", "comments"}},
		{ID: "canva", Name: "Canva", Category: "Design", Kind: "custom_api", Description: "Designs, modelos e exportação de artes.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"designs"}},
		{ID: "mailchimp", Name: "Mailchimp", Category: "Marketing", Kind: "custom_api", Description: "Audiências, campanhas de e-mail e relatórios; envio exige approval.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"audiences", "campaigns"}},
		{ID: "salesforce", Name: "Salesforce", Category: "CRM e Vendas", Kind: "custom_api", Description: "Contas, contatos, oportunidades e relatórios.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"accounts", "opportunities"}},
		{ID: "zoom", Name: "Zoom", Category: "Comunicação", Kind: "custom_api", Description: "Reuniões, gravações e transcrições.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"meetings", "recordings"}},
		{ID: "paypal", Name: "PayPal", Category: "Pagamentos", Kind: "custom_api", Description: "Pedidos, pagamentos e reembolsos; movimentações exigem approval.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"orders", "payments"}},
		{ID: "mercado-pago", Name: "Mercado Pago", Category: "Pagamentos", Kind: "custom_api", Description: "Cobranças, Pix, links de pagamento e conciliação; movimentações exigem approval.", Auth: "api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"payments", "pix"}},
		{ID: "supabase", Name: "Supabase", Category: "Desenvolvimento", Kind: "custom_api", Description: "Projetos, banco Postgres, storage e edge functions.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"projects", "database"}},
		{ID: "wordpress", Name: "WordPress", Category: "Marketing", Kind: "custom_api", Description: "Posts, páginas e mídia via REST API; publicação exige approval.", Auth: "api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"posts", "media"}},
		{ID: "calendly", Name: "Calendly", Category: "Produtividade", Kind: "custom_api", Description: "Tipos de evento, agenda e convidados.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"events"}},
		{ID: "typeform", Name: "Typeform", Category: "Dados e métricas", Kind: "custom_api", Description: "Formulários e respostas.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"forms", "responses"}},
		{ID: "zendesk", Name: "Zendesk", Category: "Suporte", Kind: "custom_api", Description: "Tickets, usuários e macros de atendimento.", Auth: "oauth_or_api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"tickets"}},
		{ID: "intercom", Name: "Intercom", Category: "Suporte", Kind: "custom_api", Description: "Conversas, contatos e artigos de ajuda.", Auth: "oauth", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"conversations"}},
		{ID: "twilio", Name: "Twilio", Category: "Comunicação", Kind: "custom_api", Description: "SMS, voz e WhatsApp via Twilio; envio exige approval.", Auth: "api_key", Source: "custom_api", Status: "operator_setup_required", Scopes: []string{"messages", "calls"}},
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	return entries
}
