/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksImport } from './routes/tasks'
import { Route as SkillsImport } from './routes/skills'
import { Route as SettingsImport } from './routes/settings'
import { Route as ScheduledImport } from './routes/scheduled'
import { Route as ProvidersImport } from './routes/providers'
import { Route as ProjectsImport } from './routes/projects'
import { Route as PluginsImport } from './routes/plugins'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LibraryImport } from './routes/library'
import { Route as ConnectorsImport } from './routes/connectors'
import { Route as ConnectImport } from './routes/connect'
import { Route as CompanyImport } from './routes/company'
import { Route as AgenticImport } from './routes/agentic'
import { Route as IndexImport } from './routes/index'
import { Route as CChatIdImport } from './routes/c.$chatId'

// Create/Update Routes

const TasksRoute = TasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const SkillsRoute = SkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ScheduledRoute = ScheduledImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRoute,
} as any)

const ProvidersRoute = ProvidersImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const PluginsRoute = PluginsImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LibraryRoute = LibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRoute,
} as any)

const ConnectorsRoute = ConnectorsImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRoute,
} as any)

const ConnectRoute = ConnectImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRoute,
} as any)

const CompanyRoute = CompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRoute,
} as any)

const AgenticRoute = AgenticImport.update({
  id: '/agentic',
  path: '/agentic',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CChatIdRoute = CChatIdImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/agentic': {
      id: '/agentic'
      path: '/agentic'
      fullPath: '/agentic'
      preLoaderRoute: typeof AgenticImport
      parentRoute: typeof rootRoute
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyImport
      parentRoute: typeof rootRoute
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectImport
      parentRoute: typeof rootRoute
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsImport
      parentRoute: typeof rootRoute
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersImport
      parentRoute: typeof rootRoute
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentic': typeof AgenticRoute
  '/company': typeof CompanyRoute
  '/connect': typeof ConnectRoute
  '/connectors': typeof ConnectorsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentic': typeof AgenticRoute
  '/company': typeof CompanyRoute
  '/connect': typeof ConnectRoute
  '/connectors': typeof ConnectorsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/agentic': typeof AgenticRoute
  '/company': typeof CompanyRoute
  '/connect': typeof ConnectRoute
  '/connectors': typeof ConnectorsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentic'
    | '/company'
    | '/connect'
    | '/connectors'
    | '/library'
    | '/onboarding'
    | '/plugins'
    | '/projects'
    | '/providers'
    | '/scheduled'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentic'
    | '/company'
    | '/connect'
    | '/connectors'
    | '/library'
    | '/onboarding'
    | '/plugins'
    | '/projects'
    | '/providers'
    | '/scheduled'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$chatId'
  id:
    | '__root__'
    | '/'
    | '/agentic'
    | '/company'
    | '/connect'
    | '/connectors'
    | '/library'
    | '/onboarding'
    | '/plugins'
    | '/projects'
    | '/providers'
    | '/scheduled'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/c/$chatId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenticRoute: typeof AgenticRoute
  CompanyRoute: typeof CompanyRoute
  ConnectRoute: typeof ConnectRoute
  ConnectorsRoute: typeof ConnectorsRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PluginsRoute: typeof PluginsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProvidersRoute: typeof ProvidersRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  CChatIdRoute: typeof CChatIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenticRoute: AgenticRoute,
  CompanyRoute: CompanyRoute,
  ConnectRoute: ConnectRoute,
  ConnectorsRoute: ConnectorsRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PluginsRoute: PluginsRoute,
  ProjectsRoute: ProjectsRoute,
  ProvidersRoute: ProvidersRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  CChatIdRoute: CChatIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/agentic",
        "/company",
        "/connect",
        "/connectors",
        "/library",
        "/onboarding",
        "/plugins",
        "/projects",
        "/providers",
        "/scheduled",
        "/settings",
        "/skills",
        "/tasks",
        "/c/$chatId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/agentic": {
      "filePath": "agentic.tsx"
    },
    "/company": {
      "filePath": "company.tsx"
    },
    "/connect": {
      "filePath": "connect.tsx"
    },
    "/connectors": {
      "filePath": "connectors.tsx"
    },
    "/library": {
      "filePath": "library.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/plugins": {
      "filePath": "plugins.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/providers": {
      "filePath": "providers.tsx"
    },
    "/scheduled": {
      "filePath": "scheduled.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/skills": {
      "filePath": "skills.tsx"
    },
    "/tasks": {
      "filePath": "tasks.tsx"
    },
    "/c/$chatId": {
      "filePath": "c.$chatId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
